### ISSUE TITLE
BackEnd Roadmap

### ISSUE THREAD

**Issue by JollyRen** [ReactThreeShowroom/api#5]
- [ ] Database:
  - [ ] has all known models needed
  - [ ] has dummy data / seed data
- [ ] API:
  - [ ] has query helpers cor CRUD on each model
  - [ ] has routes
  - [ ] gatekeeping middleware created
  - [ ] gatekeeping middleware implemented
  - [ ] error handling with correct status codes
  - [ ] sends meaningful data back

- [ ] 3D models
  - [ ] sourced or kept in accessible location (S3, etc.)
  - [ ] single file type used
